CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    version BIGINT
);

CREATE TABLE IF NOT EXISTS addresses (
    user_id BIGINT,
    line1 VARCHAR,
    line2 VARCHAR,
    city VARCHAR,
    province VARCHAR,
    postal_code VARCHAR,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
