apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: library-api-gateway
  name: library-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: library-api-gateway
    spec:
      containers:
      - image: localhost:32000/library-api-gateway
        name: library-api-gateway
        resources: {}
        readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        volumeMounts:
          - name: library-api-gateway-config-volume
            mountPath: /workspace/config
      volumes:
        - name: library-api-gateway-config-volume
          configMap:
            name: library-api-gateway-config
status: {}
