apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yml
- deployment.yml

generatorOptions:
  disableNameSuffixHash: true 

configMapGenerator:
  - name: library-api-gateway-config
    files:
      - application.yml
