apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: author-service
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: localhost:32000/author-service
    custom:
      buildCommand: ./mvnw spring-boot:build-image -DskipTests=true && docker push $IMAGE
      dependencies:
        paths:
          - pom.xml
          - src
deploy:
  kustomize:
    paths: 
    - kustomize/base
profiles:
  - name: local
    deploy:
      kustomize:
        paths:
          - kustomize/local
  - name: slow
    deploy:
      kustomize:
        paths:
          - kustomize/slow
