# docker-compose.yml
version: '3.3'
services:
  actuator-demo:
    image: ryanhhtan/spring-actuator-demo
    networks:
      - demo
    ports:
      - '8080:8080'
      - '8081:8081'
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - demo
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    networks:
      - demo
    ports:
      - '3000:3000'

networks:
  demo:
