spring:
  datasource:
    url: jdbc:postgresql://prod-postgres/book_service
    username: postgres
    password: example 
  jpa:
    hibernate:
      ddl-auto: validate
  cloud.stream:
    # function:
    #   bindings:
    #     handleAuthorEvent-in-0: authorEvent
    source: sendBookEvent;handleAuthorEvent
    bindings:
      sendBookEvent-out-0:
        destination: book-service-book-domain-events
      handleAuthorEvent-in-0:
        destination: author-service-author-domain-events
    kafka.binder.brokers:
    - dev-kafka


server.error.include-message: always
management:
  endpoints.web.exposure.include: '*'
  server.port: 8081
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
