spring:
  datasource:
    url: jdbc:postgresql://prod-postgres/book_service
    username: postgres
    password: example 
  jpa:
    hibernate:
      ddl-auto: validate
server.error.include-message: always
management:
  server.port: 8081
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
