apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: book-service
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: book-service
    spec:
      containers:
      - image: localhost:32000/book-service
        name: book-service
        resources: {}
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            port: 8081
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
status: {}
