apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - enable_local_profile.yml

configMapGenerator:
  - name: book-service-local
    files:
      - application.yml
