apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-actuator-demo
  name: spring-actuator-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-actuator-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-actuator-demo
    spec:
      containers:
      - image: localhost:32000/spring-actuator-demo:registry
        name: spring-actuator-demo
        resources: {}
        readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
          
status: {}
