spring:
  # main.lazy-initialization: true
  application:
    name: author-service
  datasource:
    url: jdbc:postgresql://prod-postgres/author_service
    username: postgres
    password: example 
  cloud.stream:
    kafka.binder.brokers:
    - dev-kafka

server.error.include-message: always
management:
  server.port: 8081
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true

