apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: author-service
  name: author-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: author-service
    spec:
      containers:
      - image: localhost:32000/author-service
        name: author-service
        resources: {}
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3
          httpGet:
            port: 8081
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
status: {}
