spring:
  datasource:
    url: jdbc:postgresql://dev-postgres.default.svc.cluster.local/book_service
    username: postgres
    password: example 
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    function:
      definition: handleAuthorEvent
    stream:
      # function:
      #   bindings:
      #     handleAuthorEvent-in-0:
      #       destination: author-service-author-domain-events
      source: sendBookEvent
      bindings:
        handleAuthorEvent-in-0:
          destination: author-service-author-domain-events
        sendBookEvent-out-0:
          destination: book-service-book-domain-events
      kafka.binder.brokers:
      - dev-kafka.default.svc.cluster.local
