apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  template:
    spec:
      containers:
        - name: book-service
          readinessProbe:
            initialDelaySeconds: 50
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 50
            periodSeconds: 5
