spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: mysql
    password: example 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION


# graphiql:
#   headers:
#     Authorization: "Bearer eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1NzI0NzgyMzAsInVzZXJfbmFtZSI6InRlc3R1c2VyMSIsImF1dGhvcml0aWVzIjpbIlRFTVBfVVNFUl9PUCJdLCJqdGkiOiI4ZTRmOWYyMi1iZjY2LTQ3ZTktOWU5My0zM2MwMTRlMzJkYzIiLCJjbGllbnRfaWQiOiJhY21lIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.N9VcvZNQL5x_GkebgJOtsAr4kqP_EK2aEXNGUdeOymWOVhU850CjU70kNrSB9_TjsaLZcdINY51faWViTmPoDlTSzP_Z2IklCCizcrROxSCt43yQ81_NpUXV0kYfsT4OEdSFooW7GUBbbmZQfVzPLUa20hN26pNlNvbyoBiADqAMA5_zYQylBEQXuQwp6rxIw09BtLBcpXCSGZvxFOIhFryqCbZJ4xP5fJ7VVhPD7x88brY2SfhkrHfYOZ5IaacIlrZENSeUTT-CILuMm0-Pi9UPl9jBR0_9RZ1pjQW-A7I8Yb3RjDAPNWX55dBEQRSedUhRIjXJyeeeUax_ASJPzw"


logging:
 level:
   org.hibernate.SQL: DEBUG
   org.hibernate.type.descriptor.sql.BasicBinder: TRACE


security:
  oauth2:
    resource:
      jwt.key-uri: https://auth.lasfu.roro3.com/oauth/token_key
