spring:
  datasource:
    url: jdbc:postgresql://localhost/gendb
    username: postgres
    password: example 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  liquibase:
    drop-first: true
  devtools:
    restart:
      enabled: true

