apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  template:
    spec:
      containers:
        - name: author-service
          readinessProbe:
            initialDelaySeconds: 40
            periodSeconds: 3
          livenessProbe:
            initialDelaySeconds: 40
            periodSeconds: 3
