spring:
  application.name: library-api-gateway
  cloud:
    gateway:
      routes:
      - id: author_route
        uri: http://author-service.default.svc.cluster.local/authors
        predicates:
        - Path=/authors**

