apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: author-service
  name: author-service
spec:
  template:
    spec:
      containers:
      - name: author-service
        env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: local
status: {}
