apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patchesStrategicMerge:
  - ./enable_local_profile.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: author-service-local
    files:
      - application.yml
