spring:
  main.lazy-initialization: true
  application:
    name: author-service
  datasource:
    url: jdbc:postgresql://dev-postgres.default.svc.cluster.local/author_service
    username: postgres
    password: example 

management:
  server.port: 8081
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
